name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install chromium  # Installs Playwright browsers

    - name: Install Allure Commandline
      run: npm install -g allure-commandline --save-dev

    - name: Run Playwright tests
      run: npx playwright test

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Print Current Directory and Files (PowerShell)
      shell: pwsh
      run: |
        Write-Output "Current Directory:"
        Get-Location
        Write-Output "Listing Files:"
        Get-ChildItem -Recurse
    
    - name: Configure Git
      if: always()
      run: |
        git config --global user.email "akashdeep.srivastava@outlook.com"
        git config --global user.name "akashdeepqa"
      
    - name: Push Allure Report to gh-pages
      if: always()
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages
        git rm -r * --ignore-unmatch
        cp -r ../allure-report/* .
        git add .
        git commit -m "Update Allure Report [$(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S IST')]"
        git push --force origin gh-pages
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30